version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: jl_strechy_database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  backup:
    image: fradelg/mysql-cron-backup
    container_name: mysql_backup
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DUMP_FREQ=1h
      - MYSQL_DUMP_BEGIN=+0
      - MYSQL_DUMP_TARGET=/backup
    volumes:
      - ./backups:/backup
    depends_on:
      - mysql

volumes:
  mysql_data:
